#pragma once
#include"framework.h"
#include"window.h"
#include"graphic.h"
#include"input.h"
#include"rand.h"
#include"MATRIX.h"
#include"VECTOR2.h"
#include"let.h"
#include"package.h"
#include"sound.h"
#include"mathUtil.h"
